#!/bin/bash
#	test1

	echo "test 1"
user=root
if grep $user /etc/passwd
then
echo "The user $user exists"
fi

#	test2


	echo "test 2"
user2=anotherUser
if grep $user2 /etc/passwd
then
echo "The user $user2 exists"
else
echo "The user $user2 doesn't exists"
fi
